version: '3.4'

services:
    client:
        build:
            context: .
            dockerfile: ./clientCalculator/Dockerfile
        network_mode: host
        expose:
            - "8080"
        ports:
            - "0.0.0.0:8080:8080"
        stdin_open: true
        tty: true

    server:
        build:
            context: .
            dockerfile: ./serverCalculator/Dockerfile
        network_mode: host
        expose:
            - "9090"
        ports:
            - "0.0.0.0:9090:9090"
        stdin_open: true
        tty: true
    
    
            