#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class OperationResult; end

class OperationResult
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CODERESULT = 1
  RESULT = 2

  FIELDS = {
    CODERESULT => {:type => ::Thrift::Types::I32, :name => 'codeResult'},
    RESULT => {:type => ::Thrift::Types::DOUBLE, :name => 'result'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

